# Generated by Django 3.1.7 on 2021-05-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210513_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_of_user',
            field=models.CharField(blank=True, choices=[('SU', 'Одиночный пользователь'), ('GM', 'Член группы'), ('TL', 'Руководитель группы')], default='SU', max_length=50),
        ),
    ]
