# Generated by Django 3.1.7 on 2021-05-25 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_status_of_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='data_of_registration',
            field=models.DateField(default=datetime.date(2021, 5, 25)),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_of_last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
