# Generated by Django 3.1.7 on 2021-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210602_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seanses',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
