# Generated by Django 3.1.7 on 2021-06-03 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210602_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_of_registration',
            field=models.DateField(default=datetime.date(2021, 6, 3)),
        ),
        migrations.AlterField(
            model_name='seanses',
            name='time_of_begin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
