# Generated by Django 3.1.7 on 2021-06-03 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210603_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='seanses',
            name='number_of_points_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seanses',
            name='number_of_points_write',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seanses',
            name='time_of_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 14, 39, 9, 164537, tzinfo=utc)),
        ),
    ]
