# Generated by Django 3.1.7 on 2021-06-03 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210603_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seanses',
            name='time_of_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 14, 52, 3, 888376, tzinfo=utc)),
        ),
    ]
