# Generated by Django 3.1.7 on 2021-06-03 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210603_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seanses',
            name='number_of_points_write',
            field=models.IntegerField(blank=True, default=777, null=True),
        ),
        migrations.AlterField(
            model_name='seanses',
            name='time_of_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 15, 46, 2, 145096, tzinfo=utc)),
        ),
    ]
