# Generated by Django 3.1.7 on 2021-06-03 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210603_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seanses',
            name='time_of_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 16, 13, 14, 925565, tzinfo=utc)),
        ),
    ]
