# Generated by Django 3.1.7 on 2021-06-04 02:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210603_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_of_registration',
            field=models.DateField(default=datetime.date(2021, 6, 4)),
        ),
        migrations.AlterField(
            model_name='seanses',
            name='time_of_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 2, 27, 34, 261196, tzinfo=utc)),
        ),
    ]
