# Generated by Django 3.1.7 on 2021-06-04 02:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210604_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seanses',
            name='number_of_points_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seanses',
            name='number_of_points_write',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seanses',
            name='time_of_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 2, 31, 39, 766797, tzinfo=utc)),
        ),
    ]
