# Generated by Django 3.1.7 on 2021-06-04 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210604_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seanses',
            name='time_of_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 2, 36, 2, 397619, tzinfo=utc)),
        ),
    ]
