# Generated by Django 3.1.7 on 2021-06-20 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210604_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100)),
                ('name_of_grouphr', models.CharField(blank=True, max_length=100)),
                ('time_of_registration', models.DateTimeField(default=datetime.datetime(2021, 6, 20, 7, 37, 2, 900641, tzinfo=utc))),
                ('comment_of_TL', models.CharField(blank=True, max_length=1000)),
                ('operating_grouphr', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='data_of_registration',
            field=models.DateField(default=datetime.date(2021, 6, 20)),
        ),
        migrations.AlterField(
            model_name='seanses',
            name='time_of_begin',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 7, 37, 2, 893637, tzinfo=utc)),
        ),
    ]
